<div id="page-wrapper" ng-controller="<?php echo $this->controle;?>_<?php echo $this->acao;?> as ctrl">
    <div class="row">
        <div class="col-lg-12">
            <?php $dados = $this->Titulo();?>
            <h1 class="page-header">
            <i class="fa fa-<?php echo $dados["icone"];?>"></i>
                <?php echo $dados["nome"];?>
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <uib-tabset>
        <uib-tab ng-repeat="tab in tabs" heading="{{tab.title}}" active="tab.active" disable="tab.disabled">
          <div class="slide-animate-container">
            <div class="slide-animate" ng-include="tab.url"></div>
          </div>
        </uib-tab>
    </uib-tabset>
</div>

