
<div id="page-wrapper" ng-controller="<?php echo $this->controle;?>_<?php echo $this->acao;?> as ctrl">
    <div class="row">
        <div class="col-lg-12">
            <?php $dados = $this->Titulo();?>
            <h1 class="page-header">
            <i class="fa fa-<?php echo $dados["icone"];?>"></i>
            <?php echo $dados["nome"];?>
            </h1>
        </div>
    </div>
    <div class="row" style="padding: 20px 0px;">
        <div class="col-lg-8 col-xs-5">
            <div>
                <?php if($this->form_cadastro):?>
                    <a uib-tooltip="Cadastrar novo grupo" href="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"form"),null,true); ?>" class="btn btn-success btn-default">Cadastrar novo</a>
                <?php endif;?>
            </div>
                  
         </div>
        <div class="col-lg-4 col-xs-7">
        
            <form name="formpesquisar" novalidate ng-submit="pesquisar()">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Pesquisar" name="pesquisa" ng-model="pesquisa" />
                  <span class="input-group-btn">
                  <a uib-tooltip="Remover filtro" ng-if="pesquisa" ng-click="removeFiltro()" href="javascript:;" class="btn btn-warning btn-default"><span class="glyphicon glyphicon-remove"></span></a>
                    <button class="btn btn-default" type="submit" uib-tooltip="Pesquisar">
                      <span class="glyphicon glyphicon-search"></span>
                    </button>
                  </span>
                  
                </div>
            </form>
            
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-xs-6">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select uib-tooltip="Muda a quantidade de listagem de grupo na tabela" id="pageSizeBinding" class="form-control" ng-model="ctrl.newPageSize" ng-options="size for size in ctrl.tableParams.settings().counts" ng-change="ctrl.changePageSize(ctrl.newPageSize)"></select>
                </div>
            </form>
        </div>
        
        <div class="col-lg-6 col-xs-6" align="right">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select uib-tooltip="Ação para os campos marcados" id="selecionados" ng-model="selecionados" ng-change="selecionar(selecionados)" class="form-control">
                    <option value="">Com selecionados:</option>
                    <?php if($this->remover):?>
                        <option value="ex">Excluir</option>
                    <?php endif;?>
                  </select>
                </div>
            </form>
        </div>
        
    </div>
    <!-- /.row -->
    <div class="row" style="padding: 10px 0px;">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table ng-table="ctrl.tableParams" class="table table-condensed table-striped table-hover table-bordered" show-filter="false">
                    <tr ng-repeat="dados in $data">
                        <td width="30" style="text-align: left" header="'ng-table/headers/checkbox.html'">
                            <input uib-tooltip="Selecionar {{dados.nm_grupo}}" type="checkbox" ng-checked="dados.selected == 'true'" ng-model="dados.selected" ng-if="dados.del == 'true'" />
                        </td>
                        <td title="'Id'" sortable="'g.id_grupo'">
                            {{dados.id_grupo}}
                        </td>
                        <td title="'Nome'" sortable="'g.nm_grupo'">
                            {{dados.nm_grupo}}
                        </td>
                        <td align="center">
                            <a uib-tooltip="Editar" href="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"form"),null,true); ?>/id/{{dados.id_grupo}}" class="btn btn-default btn-sm" ><span class="glyphicon glyphicon-pencil"></span></a> 
                            <button confirm-click="Want to see a popup?" uib-tooltip="Deletar" ng-if="dados.del == 'true'" class="btn btn-danger btn-sm" ng-click="ctrl.del($event,$index)"><span class="glyphicon glyphicon-trash"></span></button>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /#page-wrapper -->

<script type="text/ng-template" id="ng-table/headers/checkbox.html">
   <input type="checkbox" uib-tooltip="Marca todos os checkbox" ng-model="checkall" ng-change="checarTodos(checkall)" class="select-all" name="filter-checkbox" value="" />
</script>
