<script>

    var $parametros = <?php echo json_encode($_POST);?>;
</script>
<hr />
<div align="center" style="padding: 10px;" load-ctrl="sca-grupo_modal" caminho-js="<?php echo $this->baseUrl($this->JsHelper())?>">
    <div class="table-responsive" ng-if="!dados.length">
    	<div style="margin-top: 10px;" role="alert" class="alert alert-info">	
    	   <strong>Oops!</strong> Nenhum arquivo encontrado
    	</div>
    </div>
    <div class="row" style="padding: 20px 0px;">
        <div class="col-lg-12">
            <form name="formpesquisar" novalidate ng-submit="pesquisar()">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Pesquisar" name="pesquisa" ng-model="pesquisa" />
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                      <span class="glyphicon glyphicon-search"></span>
                  </button>
                  </span>
                </div>
            </form>
        </div>
    </div>
    <div class="row" style="padding: 10px 0px;">
        <div class="col-lg-12">
            <table ng-table="tableParams" class="table table-condensed table-striped table-hover table-bordered" show-filter="false">
                <tr ng-repeat="dados in $data" ng-click="addSelecao({id_grupo:dados.id_grupo,nm_grupo:dados.nm_grupo})" style="cursor: pointer;">
                    <td title="'Id'" sortable="'u.id_grupo'">
                        {{dados.id_grupo}}
                    </td>
                    <td title="'Nome'" sortable="'u.nm_grupo'">
                        {{dados.nm_grupo}}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <hr />
</div>

