<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	
<div class="modal-dialog modal-sm">
	<div class="modal-content">
	    <form action="javascript:;" id="frmEdicaoRapida" class="form formAjax" data-action="cadastrar-acao" data-ctrl="<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>" data-modulo="<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">X</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Cadastro Rápido</h4>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Nome</label>
				<input type="text" name="nome" id="nomeEditar" class="form-control validate[required]">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Status</label>
				<select name="status" id="usuario_grupo_idEditar input-md required" class="form-control">
			       <option value="0">Inativo</option>
			       <option value="1">Ativo</option>
			    </select>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Email</label>
				<input type="text" name="email" id="emailEditar" class="form-control validate[required,custom[email]]">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Senha</label>
				<input type="password" name="senha" id="senhaEditar" class="form-control validate[required]">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Telefone</label>
				<input type="text" name="telefone" id="telefoneEditar" class="form-control validate[required]" mask-input="telefone">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Data de Nascimento</label>
				<input type="text" name="data_nascimento" id="data_nascimentoEditar" class="form-control validate[required]" mask-input="data">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Cidade</label>
				<input type="text" name="cidade" id="cidadeEditar" class="form-control validate[required]">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Bairro</label>
				<input type="text" name="bairro" id="bairroEditar" class="form-control validate[required]">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
              <label>Avisar Usuário por e-mail?</label>
              <div class="checkbox">
                <label for="avisar-0">
                  <input name="avisar" id="avisar-0" value="1" type="radio">
                  Sim
                </label>
            	</div>
              <div class="checkbox">
                <label for="avisar-1">
                  <input name="avisar" id="avisar-1" checked="checked" value="0" type="radio">
                  Não
                </label>
            	</div>
            </div>
			<div class="modal-footer" style="margin-top: 5px;">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="submit" class="btn btn-primary">Cadastrar</button>
			</div>
		</form>
	</div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->
