<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="pt-BR" />
        <meta http-equiv="Cache-Control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta name="robots" content="ALL" />
        <meta name="keywords" content="<?php //echo $this->headTags(); ?>" />
        <meta name="description" content="<?php //echo $this->headDescricao(); ?>"/>
        <meta name="resource-types" content="document" />
        <meta name="revisit-after" content="1 day" />
        <meta name="distribution" content="Global" />
        <meta name="rating" content="General" />
        <meta name="author" content="Paulo" />
        <meta name="language" content="pt-br" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="http://www.netsuprema.com.br/net.ico" />
        
        <?php $this->headScript()->appendFile('http://html5shim.googlecode.com/svn/trunk/html5.js','text/javascript',array('conditional' => 'if lt IE 9'));?>
        
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/bootstrap/dist/css/bootstrap.min.css') ?> 
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/components-font-awesome/css/font-awesome.min.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/template1/padrao.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/template1/hover-min.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/template1/multiple-select-master/multiple-select.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/colorPicker/css/bootstrap-colorpicker.min.css') ?>
        
        
        <script>
			var pathSite = '<?php echo $this->baseUrl() ?>';
			var Controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';
			var Modulo = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>';
        </script>
        
        <?php
            echo $this->headScript()->appendFile($this->baseUrl('js/bower_components/jquery/dist/jquery.min.js'))
                                      ->appendFile($this->baseUrl('js/bower_components/bootstrap/dist/js/bootstrap.min.js'))
                                      ->appendFile($this->baseUrl('js/template1/jquery.jeditable.mini.js'))
                                      ->appendFile($this->baseUrl('js/template1/multiple-select-master/jquery.multiple.select.js'))
                                      ->appendFile($this->baseUrl('js/bower_components/colorPicker/js/bootstrap-colorpicker.min.js'))
                                      ->appendFile($this->baseUrl('js/template1/scripts.js'));
        ?>

        
        <link rel="canonical" href="<?=isset($_SERVER['SCRIPT_URI'])?>" />

		<?php echo $this->headMeta(); ?>
		<title>PAINEL ADMINISTRATIVO - SIG</title>
		<?php echo $this->headLink(); ?>
	</head>
	<body>
		<div class="faixaTop cTopo"></div>
		<header class="cBgTopo">
			<div class="container">
			    <div class="row">
			        <div class="col-sm-4 col-xs-5 col-lg-4">
			            <div style="padding: 15px;">
        					<img src="<?php echo $this->baseUrl('img/template1/topo/logo.png'); ?>" class="img-responsive" border="0" alt="#">
    					</div>
    				</div>
    				<div class="col-sm-12 col-xs-12 col-lg-8">
			            <div class="row">
			                <div class="col-sm-12 col-xs-12 col-lg-12" align="right">
			                    <ul class="list-inline menuTopo cMenu1">
                					<li>
                						<a href="javascript:;">
                							Página Inicial
                						</a>
                					</li>
                					
                					<li>
                						<a href="javascript:;">
                							A Empresa
                						</a>
                					</li>
                					
                					<li>
                						<a href="javascript:;">
                							Serviços
                						</a>
                					</li>
                					
                					<li>
                						<a href="javascript:;">
                							2º Via de Boletos
                						</a>
                					</li>
                					
                					<li>
                						<a href="javascript:;">
                							Contato
                						</a>
                					</li>
                				</ul>
			                </div>
			                <div class="col-sm-12 col-xs-12 col-lg-12" align="right">
                				<div class="foneTopo cTelefoneTopo">
                					<i class="fa fa-phone iconeFoneTopo"></i> 
                					<span class="edtiTelefone cTelefoneTopo">(62) 3092-4050</span>
                				</div>
			                </div>
			            </div>
    				</div>
				</div>	
				<div class="row">
				    <div class="col-sm-12 col-xs-12 col-lg-12">
        				<div class="menuRapidoTopo">
        					<a href="#" class="textoMenuRapidoTopo cMenu2">
        						<i class="fa fa-calendar"></i> Agende uma visita
        					</a>
        				</div>
        				<div class="menuRapidoTopo">
        					<a href="#" class="textoMenuRapidoTopo cMenu2">
        						<i class="fa fa-phone"></i> Ligamos pra você
        					</a>
        				</div>
        				<div class="menuRapidoTopo">
        					<a href="#" class="textoMenuRapidoTopo cMenu2">
        						<i class="fa fa-envelope"></i> Envie um e-mail 
        					</a>
        				</div>
        				<div class="menuRapidoTopo">
        					<a href="#" class="textoMenuRapidoTopo cMenu2">
        						<i class="fa fa-comments"></i> Corretor OnLine
        					</a>
        				</div>
        				<div style="clear: both;"></div>
    				</div>
				</div>		
			</div>		
		</header>
        <div class="banner cFatiaBanner">
        	<div class="container">
        		<div class="row">
        		    <div class="col-sm-12 col-xs-12 col-lg-12">
        		        <ul class="list-unstyled">
            				<li>
            				    <img class="img-responsive" src="<?php echo $this->baseUrl('img/template1/banner/1.jpg'); ?>" alt="img02"/>
            				</li>
            			</ul>
        		    </div>
        		</div>
        	</div>
        </div>
        <div class="buscaImovelIndex cbgPesquisa">
        	<div class="container">
        	    <div class="row">
        	        <div class="col-sm-6 col-xs-12 col-lg-6">
        	            <div class="tituloBuscaIndex cbgPesquisa1Titulo">
                			Busca de imóveis <i class="fa fa-search"></i>
                		</div>
        	        </div>
        	        <div class="col-sm-6 col-xs-12 col-lg-6" align="right">
        	            <div class="row">
        	                <div class="col-sm-5 col-xs-12 col-lg-8" align="right">
        	                    <input type="text" name="buscaCodigo" id="buscaCodigo" class="imputBuscaIndex class1"/>
        	                </div>
        	                <div class="col-sm-7 col-xs-12 col-lg-4" align="right">
        	                    <a href="javascript:;" class="botBuscaIndex cBgBotaoPesquisa1 class2 cBgBotaoPesquisa1Texto">
                        			 Buscar por código
                        		</a>
        	                </div>
        	            </div>
        	            
        	            
        	        </div>
        	    </div>
        	    <div class="row" style="margin-top: 25px;">
        	        <form class="espaco_form_busca" action="/imovel/busca" method="post" name="form_busca" id="form_busca">
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <select style="width: 100%;">
            	                <option selected="selected">Teste</option>
            	                <option>Teste</option>
            	            </select>
            	        </div>
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <select data-placeholder="Categoria" style="width: 100%;" multiple="multiple">
            	                <option>Teste</option>
            	                <option>Teste</option>
            	            </select>
            	        </div>
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <select data-placeholder="Tipo" style="width: 100%;" multiple="multiple">
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	            </select>
            	        </div>
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <select data-placeholder="Preço" style="width: 100%;">
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	            </select>
            	        </div>
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <select data-placeholder="Cidade" style="width: 100%;" multiple="multiple">
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	                <option>Teste</option>
            	            </select>
            	        </div>
            	        <div class="col-sm-2 col-xs-12 col-lg-2">
            	            <div class="row">
            	                <div class="col-sm-6 col-xs-12 col-lg-8">
            	                    <select data-placeholder="Bairro" disabled="disabled" style="width: 100%;" multiple="multiple">
                    	                <option>Teste</option>
                    	                <option>Teste</option>
                    	                <option>Teste</option>
                    	                <option>Teste</option>
                    	            </select>
            	                </div>
            	                <div class="col-sm-6 col-xs-12 col-lg-4">
            	                    <a class="botFormBusca btPesquisa1Sai cBgBotaoPesquisa1" href="javascript:;" title="Invest Imobiliária - imóveis em Marabá">
            							<i class="fa fa-search saiIcone cBgBotaoPesquisa1Texto"></i>
            			        	</a>
            	                </div>
            	            </div>
            	            
            	        </div>
        	        </form>
        	    </div>
        	</div>
        	<style>
        	    .btPesquisa1Sai{
        	    	color:#FFF; 
        	    	text-align:center; 
        	    	display: block; 
        	    	width: 100%; 
        	    	border-radius:5px; 
        	    	text-decoration: none;
        	    }
        	    
        	    .saiIcone{
        	    	color:#fff; 
        	    	padding: 6px 0px;
        	    }
        	</style>
        </div>
        <!-- Fim Busca do Imóvel -->
        
        <!-- TABS -->
        <div> 
            <div class="container">
                <div class="tabbable-panel">
    				<div class="tabbable-line">
    					<ul class="nav nav-tabs ">
    					    <?php for($i=0;$i<3;$i++):?>
    						<li class="<?php echo $i == 0 ? 'active' : '';?>">
    							<a href="#tab_default_<?php echo $i;?>" data-toggle="tab">
    							    Venda
    							</a>
    						</li>
    						<?php endfor;?>
    					</ul>
    					<div class="tab-content">
    					    <?php for($i=0;$i<3;$i++):?>
    						<div class="tab-pane active" id="tab_default_<?php echo $i;?>">
                                <div class="row">
                                    <?php for($i=0;$i<8;$i++):?>
                                    <div class="col-sm-6 col-xs-12 col-lg-3">
                                        <div class="thumbnail class_box_shadow">
                                              <div class="well" style="margin-bottom: 3px;">
                                                  <div style="height: 200px; overflow: hidden;">
                                                      <a href="javascript:;" class="hvr-pop" style="width: 100%; display: block;">
                                                          <img src="http://investmaraba.com.br/media/upload/imagens/i31_21.jpg" class="img-responsive" alt="..."/>
                                                      </a>
                                                  </div>
                                              </div>
                                              <div class="caption">
                                                <h4 style="text-overflow: ellipsis; overflow:hidden; margin-top: 0px;">
                                                    <a href="javascript:;" class="cCorpoTextoImovel">
                                                        <i class="fa fa-home"></i>
                                                        Text aqui
                                                    </a>
                                                </h4>
                                                <p style="text-overflow: ellipsis; overflow:hidden;">
                                                    Text aqui Text aqui Text aqui Text aqui Text aqui
                                                </p>
                                                <p>
                                                    <a href="javascript:;" class="cCorpoTextoImovel">
                                                        <i class="fa fa-money"></i>
                                                        R$ 1500,00
                                                    </a>
                                                </p>
                                                <div align="right">
                                                    <a href="#" class="btn btn-default hvr-float-shadow" role="button">
                                                        <i class="fa fa-plus-square-o"></i>
                                                        Detalhes
                                                    </a>
                                                </div>
                                              </div>
                                        </div>
                                    </div>
                                    <?php endfor;?>
                                </div>
    						</div>
    						<?php endfor;?>
    					</div>
    				</div>
    			</div>
            </div>
        </div>

		<footer>
        	<div style="width: 100%; height: 300px; background: #000;">
        	    <div class="container">
            	    <div class="row">
                	    <div class="col-lg-3 col-md-6">
            			<h3>Menu:</h3>
                            <ul>
                				<li><a href=""><i class="fa fa-file"></i> News</a></li>
                				<li><a href=""><i class="fa fa-android"></i> Android</a></li>
                				<li><a href=""><i class="fa fa-code"></i> C#</a></li>
                				<li><a href=""><i class="fa fa-code"></i> Java</a></li>
                				<li><a href=""><i class="fa fa-book"></i> Books</a></li>
                				<li><a href=""><i class="fa fa-globe"></i> Web</a></li>
                				<li><a href=""><i class="fa fa-windows"></i> Windows</a></li>
            				</ul>
                        </div>
            
                        <div class="col-lg-3 col-md-6">
                            <h3>Contato:</h3>
            				<p>Have a question or feedback? Contact me!</p>
            				<p><a href="" title="Contact me!"><i class="fa fa-envelope"></i> Contact</a></p>
            			</div>
            			
            			<div class="col-lg-3 col-md-6">
                            <h3>Rede Social:</h3>
            				<ul class="list-inline">
                                <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                                <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                                <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                                <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                                <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                            </ul>
            			</div>
            			<div class="col-lg-3 col-md-6">
                            <h3>Receba Novidades:</h3>
                            <div class="row">
                                <div class="col-sm-6 col-xs-12 col-lg-9">
                                    <input type="text" name="buscaCodigo" id="buscaCodigo" class="imputBuscaIndex" style="margin-right: 10px; width: 100%;"/>
                                </div>
                                <div class="col-sm-6 col-xs-12 col-lg-3">
                                    <a style="background:#fff;color:#000; text-align:center; display: block; width: 100%; height:35px; margin-top:15px; border-radius:5px; text-decoration: none;" class="botFormBusca" href="javascript:;" title="Invest Imobiliária - imóveis em Marabá">
            							<i style="color:#000; padding: 10px 0px;" class="fa fa-search"></i>
            			        	</a>
                                </div>
                                
                            </div>
            			</div>
        			</div>
    			</div>
        	</div>
		</footer>
        
        <nav class="animate">
            <form class="form-horizontal formAjax" action="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/cadastrar-acao/type/json">
                <div style="padding: 15px;">
    		        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                      <div class="panel panel-default">
                        <div class="panel-heading" role="tab">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#topoEditar" aria-expanded="true" aria-controls="collapseOne">
                              Topo
                            </a>
                          </h4>
                        </div>
                        <div id="topoEditar" class="panel-collapse collapse in" role="tabpanel">
                          <div class="panel-body">
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Fatia do Topo</label>
                              <div class="col-md-12">
                                <div class="input-group sCTopo">
                                    <input type="text" name="topo_fatia" value="<?php echo $this->template_opcao['topo_fatia'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Topo</label>
                              <div class="col-md-12">
                                <div class="input-group sCBgTopo">
                                    <input type="text" name="topo_bg" value="<?php echo $this->template_opcao['topo_bg'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Fonte do Menu </label>
                              <div class="col-md-6">
                                <div class="input-group sCMenu1">
                                    <input type="text" name="topo_fonte_menu1" value="<?php echo $this->template_opcao['topo_fonte_menu1'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="input-group sCMenu1Hover">
                                    <input type="text" name="topo_fonte_menu1_hover" value="<?php echo $this->template_opcao['topo_fonte_menu1_hover'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Telefone Topo </label>
                              <div class="col-md-12">
                                <div class="input-group sCTelefoneTopo">
                                    <input type="text" name="topo_telefone" value="<?php echo $this->template_opcao['topo_telefone'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Fonte do Menu 2 </label>
                              <div class="col-md-6">
                                <div class="input-group sCMenu2">
                                    <input type="text" name="topo_fonte_menu2" value="<?php echo $this->template_opcao['topo_fonte_menu2'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="input-group sCMenu2Hover">
                                    <input type="text" name="topo_fonte_menu2_hover" value="<?php echo $this->template_opcao['topo_fonte_menu2_hover'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Banner </label>
                              <div class="col-md-12">
                                <div class="input-group sCFatiaBanner">
                                    <input type="text" name="topo_bg_banner" value="<?php echo $this->template_opcao['topo_bg_banner'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="panel panel-default">
                        <div class="panel-heading" role="tab">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#pesquisaEditar" aria-expanded="true" aria-controls="collapseOne">
                              Pesquisa
                            </a>
                          </h4>
                        </div>
                        <div id="pesquisaEditar" class="panel-collapse collapse" role="tabpanel">
                          <div class="panel-body">
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Fatia da Pesquisa </label>
                              <div class="col-md-12">
                                <div class="input-group sCbgPesquisa">
                                    <input type="text" value="<?php echo $this->template_opcao['pesquisa_bg'];?>" name="pesquisa_bg" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Título Buscar Pesquisa </label>
                              <div class="col-md-12">
                                <div class="input-group sCbgPesquisa1Titulo">
                                    <input type="text" value="<?php echo $this->template_opcao['pesquisa_titulo'];?>" name="pesquisa_titulo" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Botao Pesquisa </label>
                              <div class="col-md-12">
                                <div class="input-group sCBgBotaoPesquisa1">
                                    <input type="text" value="<?php echo $this->template_opcao['pesquisa_bt'];?>" name="pesquisa_bt" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Botao Pesquisa Texto </label>
                              <div class="col-md-12">
                                <div class="input-group sCBgBotaoPesquisa1Texto">
                                    <input type="text" value="<?php echo $this->template_opcao['pesquisa_bt_texto'];?>" name="pesquisa_bt_texto" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="panel panel-default">
                        <div class="panel-heading" role="tab">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#corpoEditar" aria-expanded="true" aria-controls="collapseOne">
                              Corpo
                            </a>
                          </h4>
                        </div>
                        <div id="corpoEditar" class="panel-collapse collapse" role="tabpanel">
                          <div class="panel-body">
                            <!-- Text input-->
                            <div class="form-group">
                              <label class="col-md-12 text-left">Texto do imóvel </label>
                              <div class="col-md-6">
                                <div class="input-group sCCorpoTextoImovel">
                                    <input type="text" value="<?php echo $this->template_opcao['corpo_texto_imovel'];?>" name="corpo_texto_imovel" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="input-group sCCorpoTextoImovelHover">
                                    <input type="text" name="corpo_texto_imovel_hover" value="<?php echo $this->template_opcao['corpo_texto_imovel_hover'];?>" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="row" style="padding: 10px 0px;">
            			<div class="col-md-12 col-xs-12 col-sm-12">
            				<div align="center" style="padding-top: 10px;">
            				    <input type="hidden" name="template_id" id="template_id" value="1"/>
            				    <input type="hidden" name="id" id="id" value="<?php echo $this->id;?>"/>
            					<button type="submit" class="btn btn-primary">Cadastrar</button>
            				</div>
            			</div>
            		  </div>
                    </div>
                </div>
            </form>
        </nav>
        
        <div class="nav-controller naoclicado">
            <span class="glyphicon glyphicon-chevron-down"></span>
        </div>
        <div class="nav-controller clicado" style="display: none;">
            <span class="glyphicon glyphicon-remove"></span>
        </div>
		<script>

		$(function() {

		    $('.sCTopo').colorpicker().on('changeColor', function(ev) {
	            $('.cTopo').css('backgroundColor',ev.color.toHex());
	        });
		    $('.sCBgTopo').colorpicker().on('changeColor', function(ev) {
	            $('.cBgTopo').css('backgroundColor',ev.color.toHex());
	        });
		    $('.sCMenu1').colorpicker().on('changeColor', function(ev) {
	            $('.cMenu1 li a').css('color',ev.color.toHex());
	        });
		    $('.sCMenu1Hover').colorpicker().on('changeColor', function(ev) {});
		    $('.sCMenu2').colorpicker().on('changeColor', function(ev) {
	            $('.cMenu2').css('color',ev.color.toHex());
	        });
		    $('.sCMenu2Hover').colorpicker().on('changeColor', function(ev) {});
		    $('.sCTelefoneTopo').colorpicker().on('changeColor', function(ev) {
	            $('.cTelefoneTopo').css('color',ev.color.toHex());
	        });
		    $('.sCFatiaBanner').colorpicker().on('changeColor', function(ev) {
	            $('.cFatiaBanner').css('backgroundColor',ev.color.toHex());
	        });
		    $('.sCbgPesquisa').colorpicker().on('changeColor', function(ev) {
	            $('.cbgPesquisa').css('backgroundColor',ev.color.toHex());
	        });
		    $('.sCbgPesquisa1Titulo').colorpicker().on('changeColor', function(ev) {
	            $('.cbgPesquisa1Titulo').css('color',ev.color.toHex());
	        });
		    $('.sCBgBotaoPesquisa1').colorpicker().on('changeColor', function(ev) {
	            $('.cBgBotaoPesquisa1').css('backgroundColor',ev.color.toHex());
	        });
		    $('.sCBgBotaoPesquisa1Texto').colorpicker().on('changeColor', function(ev) {
	            $('.cBgBotaoPesquisa1Texto').css('color',ev.color.toHex());
	        });
		    $('.sCCorpoTextoImovel').colorpicker().on('changeColor', function(ev) {
	            $('.cCorpoTextoImovel').css('color',ev.color.toHex());
	        });
		    $('.sCCorpoTextoImovelHover').colorpicker().on('changeColor', function(ev) {});
		    
		});

		$(document).ready(function(){
		    $(".naoclicado").click(function(){
		        $(this).css('display','none');
		        $('.clicado').css('display','');
		        $('.animate').css('right','0');
		        return false;
		    });
		    $(".clicado").click(function(){
		        $(this).css('display','none');
		        $('.naoclicado').css('display','');
		        $('.animate').css('right','-100%');
		        return false;
		    });
		});
		    /*$('#colorpickerField1').colorpicker({
	            color: '#fff',
	            format: 'rgba'
	        }).on('changeColor', function(ev) {
	            $(this).css('backgroundColor',ev.color.toHex());
	        }).on('hidePicker',function(){
	            alert('sai');
	        });*/

		    /*$('header').colorpicker({
	            color: '#fff'
	        }).on('changeColor', function(ev) {
	            $(this).css('backgroundColor',ev.color.toHex());
	        }).on('hidePicker',function(){
	            alert('sai');
	        });*/
		</script>
		<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>" media="screen" rel="stylesheet" type="text/css"/>
		<link href="<?php echo $this->baseUrl('painel/cs-template/css') ;?>" media="screen" rel="stylesheet" type="text/css"/>
        <script type="text/javascript" src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
    </body>
</html>