
<div load-ctrl="<?php echo $this->controle;?>_<?php echo $this->acao;?>" caminho-js="<?php echo $this->baseUrl($this->JsHelper())?>">
    
    <?php //echo $this->form->start($this->helper->getFormName(), null, 'post', array('class' => 'form-horizontal')); ?>
    <form action="" id="form" novalidate="novalidate">
		<div class="form-group">
			<label for="id_usuario" class="col-sm-2 col-xs-12 control-label">Usuário:</label>
			<div class="col-sm-2 col-xs-12 col-lg-1">
				<input name="id_usuario" disabled="disabled" ng-model="dados.id_usuario" class="form-control"/>
			</div>
			<?php if(Zend_Registry::get('acl')->isAllowed($this->sessao->id_grupo, $this->controle, "modal")):?>
			<div class="col-sm-7 col-xs-12 col-lg-8">
				<input name="nm_usuario" ng-model="dados.nm_usuario" data-error="Nome do usuário obrigatório" data-type="string" required class="form-control"/>
			</div>
			<div class="col-sm-1 col-xs-12 col-lg-1">
				<lookup islocation="id_usuario" returncontrole="<?php echo $this->controle;?>_<?php echo $this->acao;?>" url="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"modal"),null,true); ?>"></lookup>
			</div>
			<?php else:?>
			<div class="col-sm-8 col-xs-12 col-lg-9">
				<input name="nm_usuario" data-error="Nome do usuário obrigatório" data-type="string" required class="form-control"/>
			</div>
			<?php endif;?>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="login_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Login:</label>
			<div class="col-sm-10 col-xs-10 col-lg-10">
				<input data-error="Login obrigatório" data-type="string" required ng-model="dados.login_usuario" name="login_usuario" class="form-control"/>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
		    <label for="id_grupo" class="col-sm-2 col-xs-12 control-label">Grupo:</label>
			<div class="col-sm-2 col-xs-12 col-lg-1">
				<input name="id_grupo" data-type="string" data-error="Id do grupo obrigatório" disabled="disabled" value="" ng-model="dados.id_grupo" class="form-control" required/>
			</div>
			<?php if(Zend_Registry::get('acl')->isAllowed($this->sessao->id_grupo, "sca-grupo", "modal")):?>
			<div class="col-sm-7 col-xs-12 col-lg-8">
				<input name="nm_grupo" ng-model="dados.nm_grupo" data-error="Grupo obrigatório" data-type="string" required class="form-control"/>
			</div>
			<div class="col-sm-1 col-xs-12 col-lg-1">
				<lookup search="nm_grupo" returncontrole="<?php echo $this->controle;?>_<?php echo $this->acao;?>" url="<?php echo $this->url(array("controller"=>"sca-grupo", "action"=>"modal"),null,true); ?>"></lookup>
			</div>
			<?php else:?>
			<div class="col-sm-8 col-xs-12 col-lg-9">
				<input name="nm_grupo" ng-model="dados.nm_grupo" data-error="Grupo obrigatório" data-type="string" required class="form-control"/>
			</div>
			<?php endif;?>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="password_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Senha:</label>
			<div class="col-sm-10 col-xs-10 col-lg-10">
				<input type="password" name="senha" data-error="Senha obrigatório" required data-type="string" class="form-control">
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="st_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Status:</label>
			<div class="col-sm-4 col-xs-10 col-lg-4">
				<select name="st_usuario" data-error="Nome obrigatório" data-type="string" required ng-model="dados.st_usuario" class="form-control">
				    <option value="0">Inativo</option>
                    <option value="1">Ativo</option>
                </select>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group" align="center">
		<botao-acao></botao-acao>
		</div>
	</form>

</div>