<div load-ctrl="<?php echo $this->controle;?>_<?php echo $this->acao;?>" caminho-js="<?php echo $this->baseUrl($this->JsHelper())?>">

    <div class="row">
    	<div class="col-md-3" style="position: relative;">
    		<img style="border:1px solid #000; width:192px; height: 192px; position: absolute; z-index: 1;" ng-src="<?php echo $this->baseUrl('assets/images/person.png')?>"/>
    		<img ngf-select ng-model="file" name="file" ngf-pattern="'image/*'"
                    ngf-accept="'image/*'" ngf-max-size="20MB" style="border:1px solid #000; width:192px; height: 192px; position: absolute; z-index: 2;" ng-src="{{croppedDataUrl}}">
    	</div>
    	<div class="col-md-9">
    		<?php //echo $this->form->start('avatar-upload', $this->url_post, 'post', array('enctype' => 'multipart/form-data')); ?>
    			<?php //echo $this->form->input('id_usuario_avatar', $this->id_usuario, 'hidden'); ?>
    			<div class="form-inline">
    				<div ngf-drop ng-model="file" ngf-pattern="image/*"
                         class="cropArea">
                        <img-crop area-min-size="192" area-type="square" image="file  | ngfDataUrl"                 
                        result-image="croppedDataUrl" ng-init="croppedDataUrl=''">
                        </img-crop>
                    </div>
    			</div>
    			<div class="form-inline">
    				<?php //echo $this->helper->botoes(array('bt-avatar-upload' => 'Enviar', 'bt-remover-avatar' => array('class' => 'btn btn-danger', 'label' => 'Remover <i class="icon-trash icon-white"></i>'))); ?>
    			</div>
    		<?php //echo $this->form->end(); ?>
    	</div>
    </div>
    
</div>
   
    <!--  <form name="myForm">
        <div>Crop Image and Upload</div>
        <button ngf-select ng-model="picFile" accept="image/*">
            Select Picture</button>
        <div ngf-drop ng-model="picFile" ngf-pattern="image/*"
             class="cropArea">
            <img-crop area-min-size="192" area-type="square" image="picFile  | ngfDataUrl"                 
            result-image="croppedDataUrl" ng-init="croppedDataUrl=''">
            </img-crop>
        </div>
        <div>
            <img ng-src="{{croppedDataUrl}}" />
        </div>
        <button ng-click="upload(croppedDataUrl)">Submit</button> 
            
        <span class="progress" ng-show="progress >= 0">
          <div style="width:{{progress}}%" ng-bind="progress + '%'"></div>
        </span>
        <span ng-show="result">Upload Successful</span>
        <span class="err" ng-show="errorMsg">{{errorMsg}}</span>
    </form>-->

    
  

</div>

</div>