<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	
<div class="container">
	<div class="jumbotron">
		<div class="row">
		<div class="col-md-12 col-xs-12 col-sm-12">
		    <div align="right">
		        <a href="javascript:history.go(-1);" class="btn btn-primary">Voltar</a>
		    </div>
		    <form action="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/editar-acao/type/json" class="form formAjax">
    		    <div id="rootwizard">
        		    <div role="tabpanel">
        
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li class="active"><a href="#modulo" data-toggle="tab" aria-expanded="true">Módulos</a></li>
                      </ul>
                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div class="tab-pane active" id="modulo">
                            <div class="row" style="padding: 10px 0px;">
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-3 control-label text-right">Nome</label>  
                                  <div class="col-md-6">
                                  <input id="nomeForm" name="nome" class="form-control input-md validate[required]" type="text" value="<?php echo $this->modulo['nome']?>">
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="padding: 10px 0px;">
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-3 control-label text-right">Font Awsome</label>  
                                  <div class="col-md-4">
                                  <select class="fontawesome-select form-control input-sm validate[required]" id="awsome" name="awsome">
                            			<?php foreach ($this->awsome() as $key => $value):?>
                            		    	<option <?php echo $key == $this->modulo['awsome'] ? 'selected="selected"' : ''; ?> value="<?php echo $key;?>"> <?php echo $value;?></option>
                            		    <?php endforeach;?>
                            	  </select>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="padding: 10px 0px;">
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-3 text-right control-label" for="statusForm">Status</label>  
                                  <div class="col-md-2">
                                      <select name="status" id="statusForm" class="form-control">
                    				     <option <?php echo !$this->modulo['status'] ? "selected='selected'" : "";?> value="0">Inativo</option>
				                         <option <?php echo $this->modulo['status'] ? "selected='selected'" : "";?> value="1">Ativo</option>
                    				  </select>
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="padding: 10px 0px;">
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-3 control-label text-right">Ordem</label>  
                                  <div class="col-md-1">
                                  <input id="ordemForm" name="ordem" class="form-control input-md validate[required]" type="text" value="<?php echo $this->modulo['ordem']?>">
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="padding: 10px 0px;">
                    			<div class="col-md-12 col-xs-12 col-sm-12">
                    				<div align="center" style="padding-top: 10px;">
                    				    <input id="moduloForm" name="modulo" class="form-control input-md validate[required]" type="hidden" value="<?php echo $this->modulo['modulo']?>">
                    				    <input type="hidden" name="id" id="idForm" value="<?php echo $this->modulo['id'];?>"/>
                    					<button type="submit" class="btn btn-primary">Alterar</button>
                    				</div>
                    			</div>
                    		</div>
                        </div>
                      </div>
                    
                    </div>
                </div>
            </form>
		
		    
		</div>    
		</div>
		

	</div>
</div>