<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('js/scripts.js')?>"></script>
	
<div class="modal-dialog modal-sm">
	<div class="modal-content">
	    <form action="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/editar-acao/type/json" class="form formAjax">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">X</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Alterar Dados</h4>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Nome</label>
				<input type="text" name="nome" id="nomeEditar" class="form-control validate[required]" value="<?php echo $this->modulo['nome']?>">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Font Awsome</label>
				<select class="fontawesome-select form-control input-sm validate[required]" id="awsome" name="awsome">
        			<?php foreach ($this->awsome() as $key => $value):?>
        		    	<option <?php echo $key == $this->modulo['awsome'] ? 'selected="selected"' : ''; ?> value="<?php echo $key;?>"> <?php echo $value;?></option>
        		    <?php endforeach;?>
        	    </select>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Status</label>
				<select name="status" id="statusForm" class="form-control">
				     <option <?php echo !$this->modulo['status'] ? "selected='selected'" : "";?> value="0">Inativo</option>
				     <option <?php echo $this->modulo['status'] ? "selected='selected'" : "";?> value="1">Ativo</option>
				</select>
			</div>
			<div class="modal-footer" style="margin-top: 5px;">
			    <input type="hidden" id="idEditar" name="id" value="<?php echo $this->modulo['id']?>"/>
			    <input type="hidden" id="ordemEditar" name="ordem" value="<?php echo $this->modulo['ordem']?>"/>
			    <input type="hidden" name="modulo" id="moduloEditar" class="form-control validate[required]" value="<?php echo $this->modulo['modulo']?>">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="submit" class="btn btn-primary">Alterar</button>
			</div>
		</form>
	</div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->
