
<div ng-controller="<?php echo $this->controle;?>_<?php echo $this->acao;?> as int">
    
    <?php //echo $this->form->start($this->helper->getFormName(), null, 'post', array('class' => 'form-horizontal')); ?>
    <form action="" id="form" novalidate="novalidate">
		<div class="form-group">
			<label for="id_usuario" class="col-sm-2 col-xs-12 control-label">Usuário:</label>
			<div class="col-sm-2 col-xs-12 col-lg-1">
				<input name="id_usuario" value="" ng-blur="loadById({id: usuario.id_usuario})" ng-model="usuario.id_usuario" class="form-control">
			</div>
			<?php if(Zend_Registry::get('acl')->isAllowed($this->sessao->grupo_id, $this->controle, "modal")):?>
			<div class="col-sm-7 col-xs-12 col-lg-8">
				<input name="nm_usuario" ng-model="usuario.nm_usuario" data-error="Nome obrigatório" data-type="string" required class="form-control">
			</div>
			<div class="col-sm-1 col-xs-12 col-lg-1">
				<lookup search="nm_usuario" controle="<?php echo $this->controle;?>_<?php echo $this->acao;?>" url="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"modal"),null,true); ?>"></lookup>
			</div>
			<?php else:?>
			<div class="col-sm-8 col-xs-12 col-lg-9">
				<input name="nm_usuario" data-error="Nome obrigatório" data-type="string" required class="form-control">
			</div>
			<?php endif;?>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="login_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Login:</label>
			<div class="col-sm-10 col-xs-10 col-lg-10">
				<input name="email" class="form-control">
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="password_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Senha:</label>
			<div class="col-sm-4 col-xs-10 col-lg-4">
				<input name="_senha" class="form-control">
			</div>
			<label for="confirmacao" class="col-sm-2 col-xs-4 col-lg-2 control-label">Confirmação:</label>
			<div class="col-sm-4 col-xs-8 col-lg-4">
				<input name="_confirmacao" class="form-control">
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group">
			<label for="st_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Status:</label>
			<div class="col-sm-4 col-xs-10 col-lg-4">
				<select name="status" class="form-control">
				    <option value="">Inativo</option>
                    <option value="1">Ativo</option>
                </select>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="form-group" align="center">
		<botao-acao></botao-acao>
		</div>
	</form>

</div>