

<div ng-controller="<?php echo $this->controle;?>_<?php echo $this->acao;?> as int" ng-init="find()">
    
    <?php //echo $this->form->start($this->helper->getFormName(), null, 'post', array('class' => 'form-horizontal')); ?>
		<div class="form-group">
			<label for="id_usuario" class="col-sm-2 col-xs-12 control-label">Usuário:</label>
			<div class="col-sm-2 col-xs-12 col-lg-1">
				<input class="form-control">
			</div>
			<div class="col-sm-8 col-xs-12 col-lg-9">
				<div class="input-group">
					<input class="form-control">
					<?php //echo $this->helper->botaoBusca('bt-listar-usuario-por-nome'); ?>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="login_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Login:</label>
			<div class="col-sm-10 col-xs-10 col-lg-10">
				<input class="form-control">
			</div>
		</div>
		<!--  <div class="alert alert-warning" role="alert">
			<strong>Atenção!</strong> Só preencha o campo "Senha" e "Confirmação" caso queira alterá-los.
		</div>-->
		<div class="form-group">
			<label for="password_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Senha:</label>
			<div class="col-sm-4 col-xs-10 col-lg-4">
				<input class="form-control">
			</div>
			<label for="confirmacao" class="col-sm-2 col-xs-4 col-lg-2 control-label">Confirmação:</label>
			<div class="col-sm-4 col-xs-8 col-lg-4">
				<input class="form-control">
			</div>
		</div>
		<div class="form-group">
			<label for="st_usuario" class="col-sm-2 col-xs-2 col-lg-2 control-label">Status:</label>
			<div class="col-sm-4 col-xs-10 col-lg-4">
				<select class="form-control">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
			</div>
		</div>
		<div class="form-group" align="center">
			<?php //echo $this->helper->botoes(array('bt-incluir' => 'Incluir', 'bt-alterar' => 'Alterar', 'bt-remover' => 'Remover'), array(array('id' => 'bt-limpar', 'label' => 'Limpar'))); ?>
		</div>
	<?php //echo $this->form->end(); ?>

</div>