<?php /*<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->titulo(new Painel_Model_CgModuloSubmenu()); ?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
	<hr />
	<div class="table-responsive">
		<?php if (isset($this->res) && is_array($this->res) && count($this->res)): ?>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th class="codigo">Código</th>
						<th class="nome">Nome</th>
						<th class="nome">Login</th>
						<th class="action"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->res as $value): ?>
						<tr>
							<td class="codigo"><?php echo $value['id_usuario']; ?></td>
							<td class="nome"><?php echo $value['nome']; ?></td>
							<td class="nome"><?php echo $value['email']; ?></td>
							<td class="action">
								<?php //if ($this->helper->hasAction('form')): ?>
									<a class="btn btn-default btn-xs" href="<?php echo $this->linkForm(array($value['id_usuario'])); ?>" role="button" title="Editar">
										<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Editar
									</a>
								<?php //endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php else: ?>
			<?php echo $this->nenhumArquivoEncontrado(); ?>
		<?php endif; ?>
	</div>
	<hr />
	<?php echo $this->paginacao($this->pages, $this->page); ?>
</div>
<!-- /#page-wrapper --> */ ?>
<?php $controle = Zend_Controller_Front::getInstance()->getRequest()->getControllerName()."_".Zend_Controller_Front::getInstance()->getRequest()->getActionName();?>
<div id="page-wrapper" ng-controller="<?php echo $controle;?> as ctrl">
    <div class="row">
        <div class="col-lg-12">
            <?php $dados = $this->Titulo();?>
            <h1 class="page-header">
            <i class="fa fa-<?php echo $dados["icone"];?>"></i>
            <?php echo $dados["nome"];?>
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row" style="padding: 20px 0px;">
        <div class="col-lg-12">
            <form name="ctrl.searchForm" novalidate ng-submit="ctrl.applyGlobalSearch()">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Pesquisar" name="searchTerm" ng-model="ctrl.globalSearchTerm" />
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" ng-disabled="ctrl.searchForm.$invalid">
                      <span class="glyphicon glyphicon-search"></span>
                  </button>
                  </span>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select id="pageSizeBinding" class="form-control" ng-model="ctrl.newPageSize" ng-options="size for size in ctrl.tableParams.settings().counts" ng-change="ctrl.changePageSize(ctrl.newPageSize)"></select>
                </div>
            </form>
        </div>
        <div class="col-lg-6" align="right">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select id="selecionados" ng-model="selecionados" ng-change="removerSelecionados(selecionados)" class="form-control">
                    <option value="">Com selecionados:</option>
                    <option value="ex">Excluir</option>
                  </select>
                </div>
            </form>
        </div>
    </div>
    <!-- /.row -->
    <div class="row" style="padding: 10px 0px;">
        <div class="col-lg-12">
            <table ng-table="ctrl.tableParams" class="table table-condensed table-striped table-hover table-bordered" show-filter="false">
                <tr ng-repeat="dados in $data">
                    <td width="30" style="text-align: left" header="'ng-table/headers/checkbox.html'">
                        <input type="checkbox" ng-model="dados.selected" ng-if="dados.del" />
                    </td>
                    <td title="'Id'" sortable="'u.id'">
                        {{dados.id}}
                    </td>
                    <td title="'Nome'" sortable="'u.nome'">
                        {{dados.nome}}
                    </td>
                    <td title="'Email'" sortable="'u.email'">
                        {{dados.email}}
                    </td>
                    <td align="center">
                        <a href="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"alterar"),null,true); ?>/id/{{dados.id}}" class="btn btn-default btn-sm" ><span class="glyphicon glyphicon-pencil"></span></a> 
                        <button ng-if="dados.del" class="btn btn-danger btn-sm" ng-click="ctrl.del($event,$index)"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<!-- /#page-wrapper -->

<script type="text/ng-template" id="ng-table/headers/checkbox.html">
        <input type="checkbox" ng-model="checkall" ng-change="checarAll(checkall)" class="select-all" name="filter-checkbox" value="" />
</script>
