<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->titulo(new Painel_Model_CgModuloSubmenu()); ?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
	<hr />
	<div class="table-responsive">
		<?php if (isset($this->res) && is_array($this->res) && count($this->res)): ?>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th class="codigo">Código</th>
						<th class="nome">Nome</th>
						<th class="nome">Login</th>
						<th class="action"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->res as $value): ?>
						<tr>
							<td class="codigo"><?php echo $value['id_usuario']; ?></td>
							<td class="nome"><?php echo $value['nome']; ?></td>
							<td class="nome"><?php echo $value['email']; ?></td>
							<td class="action">
								<?php //if ($this->helper->hasAction('form')): ?>
									<a class="btn btn-default btn-xs" href="<?php echo $this->linkForm(array($value['id_usuario'])); ?>" role="button" title="Editar">
										<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Editar
									</a>
								<?php //endif; ?>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php else: ?>
			<?php echo $this->nenhumArquivoEncontrado(); ?>
		<?php endif; ?>
	</div>
	<hr />
	<?php echo $this->paginacao($this->pages, $this->page); ?>
</div>
<!-- /#page-wrapper -->
