
<div id="page-wrapper" ng-controller="<?php echo $this->controle;?>_<?php echo $this->acao;?> as ctrl">
    <div class="row">
        <div class="col-lg-12">
            <?php $dados = $this->Titulo();?>
            <h1 class="page-header">
            <i class="fa fa-<?php echo $dados["icone"];?>"></i>
            <?php echo $dados["nome"];?>
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row" style="padding: 20px 0px;">
        <?php if($this->form_cadastro):?>
        <div class="col-lg-12">
            <div style="margin:10px 0px;">
                <a href="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"form"),null,true); ?>" class="btn btn-success btn-sm">Cadastrar novo <span class="glyphicon glyphicon-plus"></span></a>
            </div>
        </div>
        <?php endif;?>
        <div class="col-lg-12">
            <form name="formpesquisar" novalidate ng-submit="pesquisar()">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Pesquisar" name="pesquisa" ng-model="pesquisa" />
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                      <span class="glyphicon glyphicon-search"></span>
                  </button>
                  </span>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select id="pageSizeBinding" class="form-control" ng-model="ctrl.newPageSize" ng-options="size for size in ctrl.tableParams.settings().counts" ng-change="ctrl.changePageSize(ctrl.newPageSize)"></select>
                </div>
            </form>
        </div>
        <?php if($this->remover):?>
        <div class="col-lg-6" align="right">
            <form class="form-inline" novalidate>
                <div class="form-group">
                  <select id="selecionados" ng-model="selecionados" ng-change="removerSelecionados(selecionados)" class="form-control">
                    <option value="">Com selecionados:</option>
                    <option value="ex">Excluir</option>
                  </select>
                </div>
            </form>
        </div>
        <?php endif;?>
    </div>
    <!-- /.row -->
    <div class="row" style="padding: 10px 0px;">
        <div class="col-lg-12">
            <table ng-table="ctrl.tableParams" class="table table-condensed table-striped table-hover table-bordered" show-filter="false">
                <tr ng-repeat="dados in $data">
                    <?php if($this->remover):?>
                    <td width="30" style="text-align: left" header="'ng-table/headers/checkbox.html'">
                        <input type="checkbox" ng-checked="dados.selected == 'true'" ng-model="dados.selected" ng-if="dados.del == 'true'" />
                    </td>
                    <?php endif;?>
                    <td title="'Id'" sortable="'u.id'">
                        {{dados.id_usuario}}
                    </td>
                    <td title="'Nome'" sortable="'u.nome'">
                        {{dados.nm_usuario}}
                    </td>
                    <td title="'Email'" sortable="'u.email'">
                        {{dados.email}}
                    </td>
                    <td align="center">
                        <a href="<?php echo $this->url(array("controller"=>$this->controle, "action"=>"form"),null,true); ?>/id/{{dados.id_usuario}}" class="btn btn-default btn-sm" ><span class="glyphicon glyphicon-pencil"></span></a> 
                        <button ng-if="dados.del == 'true'" class="btn btn-danger btn-sm" ng-click="ctrl.del($event,$index)"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<!-- /#page-wrapper -->

<script type="text/ng-template" id="ng-table/headers/checkbox.html">
        <input type="checkbox" ng-model="checkall" ng-change="checarTodos(checkall)" class="select-all" name="filter-checkbox" value="" />
</script>
