<?php //echo $this->helper->paginacao($this->pages, $this->page); ?>
<hr />
<div align="center" style="padding: 10px;" ng-controller="ca-usuario_aba-usuario as int">
    <div class="table-responsive">
    	<?php if (isset($this->dados['res']) && is_array($this->dados['res']) && count($this->dados['res'])): ?>
    		<table class="table table-striped table-hover">
    			<thead>
    				<tr>
    					<th class="codigo">Código</th>
    					<th class="nome">Nome</th>
    					<th class="nome">Email</th>
    				</tr>
    			</thead>
    			<tbody>
    				<?php foreach ($this->dados['res'] as $value): ?>
    					<tr ng-click="modalSelect({id_usuario:'<?php echo $value['id_usuario']; ?>',nm_usuario:'<?php echo $value['nm_usuario']; ?>'})" style="cursor: pointer;">
    						<td><?php echo $value['id_usuario']; ?></td>
    						<td><?php echo $value['nm_usuario']; ?></td>
    						<td><?php echo $value['email']; ?></td>
    					</tr>
    				<?php endforeach; ?>
    			</tbody>
    		</table>
    	<?php else: ?>
    		<?php echo $this->nenhumArquivoEncontrado(); ?>
    	<?php endif; ?>
    </div>
    <hr />
</div>
<?php //echo $this->helper->paginacao($this->pages, $this->page); ?>
