<?php /*<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="pt-BR" />
        <meta http-equiv="Cache-Control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta name="robots" content="ALL" />
        <meta name="keywords" content="<?php //echo $this->headTags(); ?>" />
        <meta name="description" content="<?php //echo $this->headDescricao(); ?>"/>
        <meta name="resource-types" content="document" />
        <meta name="revisit-after" content="1 day" />
        <meta name="distribution" content="Global" />
        <meta name="rating" content="General" />
        <meta name="author" content="Paulo" />
        <meta name="language" content="pt-br" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="http://www.netsuprema.com.br/net.ico" />
        
        <?php $this->headScript()->appendFile('http://html5shim.googlecode.com/svn/trunk/html5.js','text/javascript',array('conditional' => 'if lt IE 9'));?>
        
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/bootstrap/dist/css/bootstrap.min.css') ?> 
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/components-font-awesome/css/font-awesome.min.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/bootstrap-modal/css/bootstrap-modal.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/js/bower_components/jQuery-Validation-Engine/css/validationEngine.jquery.css') ?>
        <?php $this->headLink()->appendStylesheet($this->baseUrl() . '/css/all.css') ?>
        
        
        <script>
			var pathSite = '<?php echo $this->baseUrl() ?>';
			var Controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';
			var Modulo = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>';
        </script>
        
        <?php
            echo $this->headScript()->prependFile($this->baseUrl('js/scripts.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/multupload/multupload.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/jQuery-Validation-Engine/js/languages/jquery.validationEngine-pt_BR.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/jQuery-Validation-Engine/js/jquery.validationEngine.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/jQuery-Mask-Plugin/dist/jquery.mask.min.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/bootstrap-modal/js/bootstrap-modalmanager.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/bootstrap-modal/js/bootstrap-modal.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/bootstrap/dist/js/bootstrap.min.js'))
                                      ->prependFile($this->baseUrl('js/bower_components/jquery/dist/jquery.min.js'));
        ?>

        
        <link rel="canonical" href="<?=isset($_SERVER['SCRIPT_URI'])?>" />

		<?php echo $this->headMeta(); ?>
		<title>PAINEL ADMINISTRATIVO - SIG</title>
		<?php echo $this->headLink(); ?>
	</head>
	<body>
	    <div id="fb-root"></div>
	    <?php if($this->mostra_head_footer):?>
	    <header>
			<!-- Static navbar -->
			<nav role="navigation" class="navbar navbar-default">
				<div class="container-fluid primary">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle" type="button">
							<span class="sr-only">Navegação</span> <span class="icon-bar"></span>
							<span class="icon-bar"></span> <span class="icon-bar"></span>
						</button>
						<a href="<?php echo $this->baseUrl() ?>/painel/index/index" class="navbar-brand"> 
							LOGO
						</a>
					</div>
					<!-- Menu -->
					<div id="bs-example-navbar-collapse-1"
						class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
						  <?php echo $this->menu() ?>
						</ul>
						<ul class="nav navbar-nav navbar-right">
						  <li>
		                    <button type="button" class="btn navbar-btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i> Configurações <span class="caret"></span></button>
		                    <ul class="dropdown-menu">
		                      <li><a href="<?php echo $this->baseUrl() ?>/painel/ca-auth/sair">Sair</a></li>
		                    </ul>
		                  </li>
						</ul>
					</div>
					<!-- /.navbar-collapse -->
				</div>
				<!-- /.container-fluid --> 
			</nav>
		</header>
		<div>
		
		</div>
		<?php endif; ?>
		<div>
    		<div class="row">
                <div class="col-xs-12" id="mensagemDenotificacao">
                    <?php $this->errorpermissao;?>
                </div>
            </div>
		    
		</div>
        <div class="container">
		    <?php echo $this->layout()->content; ?>
		</div>
		
		<?php if($this->mostra_head_footer):?>
		<footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Painel Administrativo © - <?php echo date('Y')?></p>
                    </div>
                </div>
            </div>
        </footer>
        <?php endif;?>
        

	</body>
</html>

*/?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <!-- MetisMenu CSS -->
    <!-- Timeline CSS -->
    <!-- Custom CSS -->
    <!-- Morris Charts CSS -->
    <!-- Custom Fonts -->
    <?php echo $this->headLink()
	    	->appendStylesheet($this->baseUrl("/bower_components/bootstrap/dist/css/bootstrap.min.css")) 
	    	->appendStylesheet($this->baseUrl("/bower_components/metisMenu/dist/metisMenu.min.css"))
			->appendStylesheet($this->baseUrl("/dist/css/timeline.css"))
			->appendStylesheet($this->baseUrl("/dist/css/sb-admin-2.css"))
			->appendStylesheet($this->baseUrl("/bower_components/morrisjs/morris.css"))
			->appendStylesheet($this->baseUrl("/bower_components/font-awesome/css/font-awesome.min.css"))
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

	<body>
		
		<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Painel Administrativo</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                    	<?php for($i=0;$i<4;$i++):?>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>Paulo</strong>
                                    <span class="pull-right text-muted">
                                        <em>22/01/2015 às 22:30</em>
                                    </span>
                                </div>
                                <div>Como ta o andamento do site?</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <?php endfor; ?>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Ver todas</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                    	<?php for($i=0;$i<4;$i++):?>
                        <li>
                            <a href="#">
                                <div>
                                    João entrou no sistema kjflksd jflkasdj lfksaj klas
                                    <br/>
                                    <span class="text-muted small">22/01/1987 às 15:00</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <?php endfor; ?>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Ver todas</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Perfil</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href=""><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="custom-search-form">
                                <input type="text" class="form-control" placeholder="Pesquisar...">
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <?php echo $this->menu() ?>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        
		<?php echo $this->layout()->content; ?>
    </div>
    <!-- /#wrapper -->
		
	
	<!-- jQuery -->
	<!-- Bootstrap Core JavaScript -->
	<!-- Metis Menu Plugin JavaScript -->
	<!-- Morris Charts JavaScript -->
	<!-- Custom Theme JavaScript -->
	<?php echo $this->headScript()->appendFile($this->baseUrl('/bower_components/jquery/dist/jquery.min.js'))
                                  ->appendFile($this->baseUrl('/bower_components/bootstrap/dist/js/bootstrap.min.js'))
								  ->appendFile($this->baseUrl('/bower_components/metisMenu/dist/metisMenu.min.js'))
								  ->appendFile($this->baseUrl('/bower_components/raphael/raphael-min.js'))
								  ->appendFile($this->baseUrl('/bower_components/morrisjs/morris.min.js'))
								  ->appendFile($this->baseUrl('/js/morris-data.js'))
								  ->appendFile($this->baseUrl('/dist/js/sb-admin-2.js'))
    ?>
	
	</body>
</html>
