
<!DOCTYPE html>
<html lang="en" ng-app="painel">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <!-- MetisMenu CSS -->
    <!-- Timeline CSS -->
    <!-- Custom CSS -->
    <!-- Morris Charts CSS -->
    <!-- Custom Fonts -->
    <?php echo $this->headLink()
	    	->appendStylesheet($this->baseUrl("/bower_components/bootstrap/dist/css/bootstrap.min.css")) 
			->appendStylesheet($this->baseUrl("/dist/css/sb-admin-2.css"))
			->appendStylesheet($this->baseUrl("/dist/css/ng-table.min.css"))
			->appendStylesheet($this->baseUrl("/dist/css/ng-img-crop.css"))
			->appendStylesheet($this->baseUrl("/dist/js/alertify/alertify.core.css"))
			->appendStylesheet($this->baseUrl("/dist/js/alertify/alertify.default.css"))
			->appendStylesheet($this->baseUrl("/bower_components/morrisjs/morris.css"))
			->appendStylesheet($this->baseUrl("/bower_components/font-awesome/css/font-awesome.min.css"))
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script>
		var _baseUrl = '<?php echo $this->baseUrl("") ?>';
		var _controller = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>';
		var _modulo = '<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>';
		var _id_usuario = '<?php echo isset(Zend_Auth::getInstance()->getIdentity()->id_usuario) ? Zend_Auth::getInstance()->getIdentity()->id_usuario : '';?>';
    </script>

</head>

	<body>
		
		<div id="wrapper">
        <?php 
        if(Zend_Auth::getInstance()->hasIdentity()):
        ?>
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header customTextCenter">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="<?php echo $this->baseUrl("assets/images/logo.png") ?>" alt="">
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle yellow" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <span class="badge bgyellow">0</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                    	<?php for($i=0;$i<4;$i++):?>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>Paulo</strong>
                                    <span class="pull-right text-muted">
                                        <em>22/01/2015 às 22:30</em>
                                    </span>
                                </div>
                                <div>Como ta o andamento do site?</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <?php endfor; ?>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Ver todas</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle green" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <span class="badge bggreen">0</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                    	<?php for($i=0;$i<4;$i++):?>
                        <li>
                            <a href="#">
                                <div>
                                    João entrou no sistema kjflksd jflkasdj lfksaj klas
                                    <br/>
                                    <span class="text-muted small">22/01/1987 às 15:00</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <?php endfor; ?>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Ver todas</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle black" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down black"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li class="text-center">
                            <img style="margin: 10px; border: 1px solid #000;" ng-src="<?php echo $this->GetDadosUsuario()['arquivo'];?>" width="150" height="150"/>
                        </li>
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Perfil</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url(array("controller"=>"index","action"=>"sair"),null,true); ?>"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                	<div class="sidebar-search">
	                	<div class="custom-search-form">
	                        <input id="txtBusca" type="text" class="form-control" placeholder="Filtrar Menu">
	                    </div>
                    </div>
                    <ul class="nav" id="side-menu">
                        <li>
                            <a class="black" href="<?php echo $this->url(array("controller"=>"index","action"=>"index"),null,true); ?>"><i class="fa fa-dashboard fa-fw black"></i> Dashboard</a>
                        </li>
                        <?php echo $this->menu(); ?>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <?php endif;?>
		<?php echo $this->layout()->content; ?>
    </div>
    <!-- /#wrapper -->
		
	
	<!-- jQuery -->
	<!-- Bootstrap Core JavaScript -->
	<!-- Metis Menu Plugin JavaScript -->
	<!-- Morris Charts JavaScript -->
	<!-- Custom Theme JavaScript -->
	<?php echo $this->headScript()->appendFile($this->baseUrl('/bower_components/jquery/dist/jquery.min.js'))
                                  ->appendFile($this->baseUrl('/bower_components/bootstrap/dist/js/bootstrap.min.js'))
								  ->appendFile($this->baseUrl('/bower_components/notify/jquery.noty.packaged.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/angular.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/ng-table.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/angular-file-upload/ng-file-upload-shim.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/angular-file-upload/ng-file-upload.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/angular-crop/ng-img-crop.js'))
								  ->appendFile($this->baseUrl('/dist/js/ui-bootstrap-tpls-0.14.3.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/webcam/webcam.min.js'))
								  ->appendFile($this->baseUrl('/dist/js/webcam/ng-camera.js'))
								  ->appendFile($this->baseUrl('/dist/js/alertify/alertify.js'))
								  ->appendFile($this->baseUrl('/dist/js/confirm-click.js'))
								  ->appendFile($this->baseUrl('/dist/js/sb-admin-2.js'))
    ?>
    <?php if($this->CssHelper()): ?>
    <link href="<?php echo $this->baseUrl($this->CssHelper());?>" media="screen" rel="stylesheet" type="text/css">
    <?php endif; ?>
    <?php if($this->JsHelper()): ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl($this->JsHelper())?>"></script>
    <?php endif; ?>
	
	</body>
</html>
