<div>
	<div class="jumbotron">
		<div>
			<div class="table-responsive" style="padding: 30px;">
				<div>
				    <div class="container">
    			        <form action="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/listar/type/json" id="frmPesquisar" class="form">
    				        <div class="row" style="padding: 10px 0px;">
                                <!-- Text input-->
                                <div class="form-group">
                                  <label class="col-md-3 control-label text-right" for="nomeForm">Atributo de pesquisa</label>  
                                  <div class="col-md-6">
                                      <input id="pesquisa"name="pesquisa" class="form-control input-md required" required type="text">
                                  </div>
                                </div>
                            </div>
                            <div class="row" style="padding: 10px 0px;">
                    			<div class="col-md-12 col-xs-12 col-sm-12">
                    				<div align="center" style="padding-top: 10px;">
                    					<button type="submit" class="btn btn-default">Pesquisar</button>
                    					<button type="button" class="btn btn-default limparForm">Limpar</button>
                    				</div>
                    			</div>
                    		</div>
                		</form>
    				</div>
				</div>
				<table id="tblflat" class="table table-hover table-striped"
					width="100%" data-toggle="table" data-show-refresh="true"
					data-side-pagination="server"
					exportTypes="['json', 'xml', 'csv', 'txt', 'sql', 'excel', 'pdf']"
					data-url="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/listar/type/json"
					data-show-export="true" data-show-columns="true"
					data-show-toggle="true" data-show-export="true"
					data-pagination="true">
					<thead>
						<tr>
							<!--             		    <th data-field="state" data-checkbox="true"></th> -->
							<th data-field="id" data-align="center" data-sortable="true">Id</th>
							<th data-field="nome" data-align="center" data-sortable="true">Nome</th>
							<th data-field="ctrl" data-align="center" data-sortable="true">Controller</th>
							<th data-field="action" data-align="center" data-sortable="true">Ação</th>
							<th data-field="modulo" data-align="center" data-sortable="true">Módulo</th>
							<th data-field="status" data-align="center" data-sortable="true">Status</th>
							<th data-field="ordem" data-align="center" data-sortable="true">Ordem</th>
							<th data-field="operate" data-width="200" data-formatter="operateFormatter" data-events="operateEvents">Ação</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-xs-12 col-sm-12">
				<div align="center" style="padding-top: 10px;">
					<a href="<?php echo $this->baseUrl() ?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/cadastro-form" class="btn btn-default">Cadastrar Novo</a>
				</div>
			</div>
		</div>

	</div>
</div>

<link href="<?php echo $this->baseUrl($this->cssHelper);?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>



<div class="modal fade forget-modal-all" tabindex="-1" role="dialog"
	aria-labelledby="myForgetModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content"></div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->
