<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('js/scripts.js')?>"></script>
	
<div class="modal-dialog modal-sm">
	<div class="modal-content">
	    <form action="<?php echo $this->baseUrl();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName();?>/editar-acao/type/json" class="form formAjax">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">X</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Alterar Dados</h4>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Nome</label>
				<input type="text" name="role" id="nomeEditar" class="form-control validate[required]" value="<?php echo $this->usuario_grupo['role']?>">
			</div>
			<div class="modal-footer" style="margin-top: 5px;">
			    <input type="hidden" id="idEditar" name="id" value="<?php echo $this->usuario_grupo['id']?>"/>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="submit" class="btn btn-primary">Alterar</button>
			</div>
		</form>
	</div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->
